wandb_version: 1

project_name:
  desc: null
  value: DDQNESWeek
env:
  desc: null
  value: test
model:
  desc: null
  value: Q-Learning
life:
  desc: null
  value: 720
steps:
  desc: null
  value: 50000
eval_frequency:
  desc: null
  value: 5000
eval_episodes:
  desc: null
  value: 3
dim:
  desc: null
  value: 10000
uavs:
  desc: null
  value: 1
clusterheads:
  desc: null
  value: 5
sensors:
  desc: null
  value: 50
disable_wandb:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711235610.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
